version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - MONGO_URL=mongodb://db:27017/instagram_clone
      - SECRET_KEY=your_jwt_secret
      - API_KEY=your_cloudinary_api_key
      - API_SECRET=your_cloudinary_api_secret
      - CLOUD_NAME=your_cloudinary_cloud_name
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://backend:8080
      - VITE_WS_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: